repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.0
    hooks:
      - id: autoflake
        args:
          [--remove-all-unused-imports, --remove-unused-variables, --in-place]
