language: python
dist: focal
os: linux
python:
  - "3.8"
  - "3.11"
addons:
  postgresql: '12'
  apt:
    packages:
      - curl
      - ffmpeg
      - postgresql-12
service:
  - docker
env:
  global:
  - PGPORT=5432
  - PGUSER=postgres
  - PGHOST=localhost
  - SQLALCHEMY_WARN_20=1
  - DEBUG=1
  - MAIL_DEBUG=1
  - FLASK_APP=zou.app
  - INDEXER_KEY="testkey0123456789"
  - PREVIEW_FOLDER=/home/travis/build/cgwire/zou/previews
before_install:
 - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
 - sudo service postgresql restart
 - sleep 1
 - pg_config --version
 - docker pull getmeili/meilisearch:v1.1
 - docker run -it --rm -d -p 7700:7700 -e MEILI_MASTER_KEY='testkey0123456789' getmeili/meilisearch:v1.1
 - curl -X POST 'http://localhost:7700/indexes' -H 'Content-Type: application/json' --data-binary '{ "uid": "assets", "primaryKey": "id" }'
 - curl -X POST 'http://localhost:7700/indexes' -H 'Content-Type: application/json' --data-binary '{ "uid": "persons", "primaryKey": "id" }'
 - curl -X POST 'http://localhost:7700/indexes' -H 'Content-Type: application/json' --data-binary '{ "uid": "shots", "primaryKey": "id" }'
install:
  - "pip install -U pip setuptools"
  - "pip install -r requirements.txt"
before_script:
  - psql -c 'create database zoudb;' -U postgres
  - mkdir /home/travis/build/cgwire/zou/previews
script: py.test
